### Vectors (Rank 1 Tensors) in NumPy

In [34]:
import numpy as np

In [35]:
x = np.array([25, 2, 5]) # type argument is optional, e.g.: dtype=np.float16
x

array([25,  2,  5])

In [36]:
len(x)

3

In [37]:
x.shape

(3,)

In [38]:
type(x)

numpy.ndarray

In [39]:
x[0] # zero-indexed

25

In [40]:
type(x[0])

numpy.int32

### Vector Transposition

In [41]:
# Transposing a regular 1-D array has no effect, since 1D array has no dimensions to be tranposed into
x_t = x.T
x_t

array([25,  2,  5])

In [42]:
x_t.shape

(3,)

In [43]:
# ...but it does we use nested "matrix-style" brackets: 
y = np.array([[25, 2, 5]])
y

array([[25,  2,  5]])

In [44]:
y.shape

(1, 3)

In [45]:
# ...but can transpose a matrix with a dimension of length 1, which is mathematically equivalent: 
y_t = y.T
y_t

array([[25],
       [ 2],
       [ 5]])

In [46]:
y_t.shape # this is a column vector as it has 3 rows and 1 column

(3, 1)

In [47]:
# Column vector can be transposed back to original row vector: 
y_t.T 

array([[25,  2,  5]])

In [48]:
y_t.T.shape

(1, 3)

### Zero Vectors

Have no effect if added to another vector

In [49]:
z = np.zeros(3) 
z

array([0., 0., 0.])

### Vectors in PyTorch and TensorFlow

In [50]:
import torch
import tensorflow as tf

In [51]:
x_pt = torch.tensor([25, 2, 5])
x_pt

tensor([25,  2,  5])

In [52]:
x_tf = tf.Variable([25, 2, 5])
x_tf

<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([25,  2,  5])>

### $L^2$ Norm

In [53]:
x

array([25,  2,  5])

In [54]:
(25**2 + 2**2 + 5**2)**(1/2)

25.573423705088842

In [55]:
np.linalg.norm(x)

25.573423705088842

So, if units in this 3-dimensional vector space are meters, then the vector $x$ has a length of 25.6m

### $L^1$ Norm

In [56]:
x

array([25,  2,  5])

In [57]:
np.abs(25) + np.abs(2) + np.abs(5)

32

### Squared $L^2$ Norm

In [59]:
x

array([25,  2,  5])

In [60]:
(25**2 + 2**2 + 5**2)

654

In [61]:
np.dot(x, x)

654

### Max Norm

In [62]:
x

array([25,  2,  5])

In [63]:
np.max([np.abs(25), np.abs(2), np.abs(5)])

25

### Orthogonal Vectors

In [64]:
i = np.array([1, 0])
i

array([1, 0])

In [65]:
j = np.array([0, 1])
j

array([0, 1])

In [66]:
np.dot(i, j)

0