### Matrices (Rank 2 Tensors) in NumPy

In [2]:
import numpy as np

# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [3]:
X.shape

(3, 2)

In [4]:
X.size

6

In [5]:
X[1,0]

5

In [6]:
X[1,:]

array([ 5, 26])

In [8]:
X[:,0]

array([25,  5,  3])

In [7]:
# Another slicing-by-index example: 
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])