### Matrices (Rank 2 Tensors) in NumPy

In [12]:
import numpy as np

# Use array() with nested brackets: 
X = np.array([[25, 2], [5, 26], [3, 7]])
X

array([[25,  2],
       [ 5, 26],
       [ 3,  7]])

In [13]:
X.shape

(3, 2)

In [14]:
X.size

6

In [15]:
X[1,0]

5

In [16]:
X[1,:]

array([ 5, 26])

In [17]:
X[:,0]

array([25,  5,  3])

In [18]:
# Another slicing-by-index example: 
X[0:2, 0:2]

array([[25,  2],
       [ 5, 26]])

### Matrices in PyTorch

In [19]:
import torch

X_pt = torch.tensor([[25, 2], [5, 26], [3, 7]])
X_pt

tensor([[25,  2],
        [ 5, 26],
        [ 3,  7]])

In [20]:
X_pt.shape # more pythonic

torch.Size([3, 2])

In [21]:
X_pt[1,:]

tensor([ 5, 26])

### Matrices in TensorFlow

In [24]:
import tensorflow as tf

X_tf = tf.Variable([[25, 2], [5, 26], [3, 7]])
X_tf

<tf.Variable 'Variable:0' shape=(3, 2) dtype=int32, numpy=
array([[25,  2],
       [ 5, 26],
       [ 3,  7]])>

In [25]:
tf.rank(X_tf)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [26]:
tf.shape(X_tf)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 2])>

In [27]:
X_tf[1,:]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 5, 26])>